=== TlahuicoleSystem/Uatx/CUERTO SEMESTRE/Diseño de Lenguajes/Ejemplos de XML/businessCarta.dtd
<!ELEMENT BusinessCards (BusinessCard+)>
<!ELEMENT BusinessCard(Name,phone,phone,email)>
<!ELEMENT Name(#PCDATA)>
<!ELEMENT phone(#PCDATA)>
<!ELEMENT phone(#PCDATA)>
<!ELEMENT email(#PCDATA)>

=== TlahuicoleSystem/Uatx/CUERTO SEMESTRE/Diseño de Lenguajes/Ejemplos de XML/BussinesCard.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/css" href="estilo.css"?>
<!DOCTYPE BusinessCards SYSTEM "businessCarta.dtd">  
	<BusinessCards>
		<BusinessCard>
		<Name>Pedro López Rugerio</Name>
		<phone type="mobile">(415) 555-4567</phone>
		<phone type="work">(800) 555-1234 </phone>
		<email> pedro@rugerio.com</email>
		</BusinessCard>

		<BusinessCard>
		<Name>Diana Pérez Rodríguez</Name>
		<phone type="mobile">(552) 2461-422</phone>
		<phone type="work">(723) 224-209 </phone>
		<email> diana@perez.com</email>
		</BusinessCard>
	</BusinessCards>
